# Generated by Django 3.2.7 on 2021-09-28 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TractorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implements', multiselectfield.db.fields.MultiSelectField(choices=[('Harrow', 'Harrow'), ('Cultivator', 'Cultivator'), ('Rotavator', 'Rotavator'), ('Plough', 'Plough'), ('Paddy Thrasher', 'Paddy Thrasher'), ('Dumping Trailer', 'Dumping Trailer'), ('4 wheel Trailer', '4 wheel Trailer')], max_length=81)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
